### PR TITLE
Add support for instant templating with shortcode

### PR DESCRIPTION
**Pull request by giovapanasiti**
this small change allows to render a template instantly without creating any post type.

example:

```html
[template]
<Loop type=post orderby=date order=desc count=6>
<div class="card">
	<Field title />
</div>
</Loop>
[/template]
```

This will work even in the classic editor

### CODE REVIEW

**Comment by eliot-akira** [comment]
Thank you for the pull request, much appreciated.

A feature like this was actually considered already, and it was an intentional decision to limit what the `template` shortcode can do.

The main concern with this feature is that it makes available the full power of templating to anyone who can write a shortcode, i.e., **non-admin users like editors**. That can lead to users without proper permissions being able to access any data, for example, WooCommerce product purchase history of another user.

This is one of the reasons why templates can only be run from a template post type, to ensure that the user writing the template has proper permissions.

Another reason is that shortcodes are often used in places where HTML is not allowed, or only partially allowed. That can lead to parts of the template getting removed or **corrupted by the HTML filter**.

So I think the convenience is not worth the risk, even as an optional plugin setting.

Maybe somewhere in the documentation this could be explained, why the `template` shortcode is limited to only loading templates written by admin users.

**Comment by giovapanasiti** [comment]
Hi @eliot-akira,  

we thought to make this change because we created the LiveCanvas builder, which is the only builder for WordPress that gives you full control over the HTML content of the page. In version 4 of the builder, we plan to integrate your `template-system` into the core of the plugin so that all our users can benefit from it.

To ensure the best possible experience, we need the `[template]` shortcode to work with an instant template. You can see a quick demo here of a prototype:

CleanShot 2024-10-03 at 23 36 59


Do you have any other solution for this to be done in a more secure way?

**Comment by jeff-at-livecanvas** [comment]
Can understand concerns about shortcodes, but alternatively, what about exposing a PHP function to help those brave guys who might want to render  LNL code programmatically? 
Would make sense to me from a templating library POV

**Comment by eliot-akira** [comment]
Fascinating, thank you for the context. The prototype of the builder integration is looking good.

> [LiveCanvas](https://livecanvas.com) builder, which is the only builder for WordPress that gives you full control over the HTML

Sound like its design and philosophy go well with the template system, whose general approach is to get back to the basics of web development with HTML and CSS (plus super powers, L&L and Sass).

The template language aims to seamlessly extend the HTML syntax - instead of a new separate syntax like most template languages do, including Gutenberg's [Block grammar](https://developer.wordpress.org/block-editor/explanations/architecture/data-flow/).

Editor Diagram

That way, existing tools and libraries for HTML, like editors and syntax highlight, already work pretty well with L&L (or Elandel) templates.

However, to take full advantage of its dynamic features, deeper editor integration would be best for user experience.

I wonder if we can **collaborate on developing open-source components** for both projects, in a way that we can all benefit from.

---

I see LiveCanvas recommends [picostrap](https://picostrap.com/), a WordPress starter theme based on Bootstrap 5.

> instantly customize it, directly from the WordPress Customizer: change colors, typography, spacings.... and preview the results immediately

How interesting, they're using [Dart Sass](https://github.com/sass/dart-sass) to compile Sass in the browser, which I've also been exploring recently - together with a Sass-first "system to build design systems" based on taking apart Bootstrap into its primitives.

I saw on the [roadmap](https://livecanvas.com/roadmap/) that you're considering [TailwindCSS](https://tailwindcss.com/) as another approach. An aspect of atomic design and utility classes that people love is how simple it is to share templates, to copy and paste as code snippets.

Thanks to a shared set of design tokens, Tailwind templates are **portable across projects** without worrying about global styles, with little to no custom CSS needed. That's valuable for templating, similar to Bootstrap's reusable templates - but going beyond it by providing all the building blocks as design primitives.

Here again, deep editor integration with the language/vocabulary would be ideal for UX, for example [Tailwind CSS IntelliSense for VSCode](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss).

I have doubts though, about putting all styles in the HTML `class` attribute, even with autocomplete and hints. It's a convenient shortcut and syntax sugar, but feels too cramped compared to writing Sass as a domain-specific language for styling. I like CSS utility classes, but for a design system I feel Sass variables are better as primitives, even more than CSS variables. (Like [Open Props](https://open-props.style/) which is an interesting approach also).

Then there's the question of integrating (or not) with WordPress core's CSS variables, Gutenberg, and `theme.json`. In an ideal world, it would be great to have a standard fully-customizable design and template system that we can all use to build WordPress sites with any theme.

But I digress..

---

> we need the `[template]` shortcode to work with an instant template

Unfortunately, for our purposes shortcodes have issues with **security** (non-admin users can run shortcodes) and **reliability** (HTML content within shortcodes is often broken or removed).

This is a fundamental limitation of how shortcodes work, they are not suitable for admin-only features like templating. There's not enough mechanism to ensure user roles and permissions; and too difficult or impossible to protect the HTML from getting corrupted by post content filters.

---

> Do you have any other solution for this to be done in a more secure way? ..What about exposing a **PHP function** to..render LNL code programmatically?

That would be a more secure way to run templates, for example, as a server response to an authenticated AJAX request.

This is the current way of rendering a "virtual" template post.

```php
$result = tangible_template_system()->render_template_post([
  'content' => $content
]);
```

It's a bit more efficient than creating a temporary `WP_Post` object.

But please note that the template system has no official **public interface for integration** yet. I'll be writing documentation about third-party integrations, which can then be considered stable and backward compatible in future versions.

---

Here's an idea: if you have a post type where builder templates are being saved, then it might be possible to **add a shortcode before rendering** it, then remove the shortcode afterwards.

As long as the template is guaranteed to be written only by admin users, or user roles which are allowed to edit templates, then they can be allowed to run that special shortcode.

However, speaking from experience, the way WordPress shortcodes are parsed using regular expressions, then filtered and rendered, is not a great fit for HTML templates. Here's a detailed comment I wrote two years ago about [numerous issues with shortcodes corrupting block HTML templates](https://core.trac.wordpress.org/ticket/55996#comment:36) and elsewhere, many still unresolved.

>  All this is related to the issue described in this ticket, where similar sets of content filters are being applied in multiple places, sometimes repeatedly on the same content. In WP 6.2.2, this is further complicated by an inconsistent order of filters. As a block author, I have certain blocks whose content should not be modified in any way, before or after rendering - but currently, it's impossible to opt-out of these filters.
>
> These content filters are causing other related issues, because they can corrupt block content in unexpected ways.

---

To conclude, I'd recommend using the `render_template_post()` function to render the HTML template. Best if it's done _instead of_ `do_shortcode` but can be before or after. This way, there's a proper HTML parser doing the job.

**Comment by jeff-at-livecanvas** [comment]
I do really appreciate your answer, and your in-depth thoughts about CSS frameworks.
[OT]
BTW, I do really feel the pain of Gutenberg and other builders bringing the user far away from HTML.
I feel like HTML is almost the writing of our era, people should be encouraged to chew it at least a but.
On a practical side, **render_template_post**() works perfectly!

**Comment by eliot-akira** [comment]
Great, I'm glad we found a solution that works for your use case. I'll go ahead and close this pull request.

I'm curious to see where this goes, I get the feeling there's potential for further collaboration between our projects. There's a similar vision with converging interests, I hope we can find a mutually beneficial symbiosis in the WordPress ecosystem.

There are many things to consider about integrating the template system with a visual builder. So far we've built extensions for [Gutenberg](https://github.com/WordPress/gutenberg/), [Elementor](https://github.com/elementor/elementor), and Beaver Builder. The first two are open-source projects, which encourages community collaboration, and I think good for the health and quality of the codebase.

Each builder has a different approach, conceptual framework, and code organization - and we've often had to adapt to their quirks, idiosyncracies, limitations.

To integrate well with LiveCanvas, I'd suggest making it an "open core" project with a public GitHub repository. (Separate from proprietary features like AI color palette generation, etc.)

Then I can read its codebase, understand how it works, and provide public functions in the template system that can be useful for its specific needs.

**Comment by jeff-at-livecanvas** [comment]
I'm sure there can be a lot of potential, 
and your views regarding open sourcing can make sense.

It's a very exciting moment as we're in the middle of a lot of work - but starting to discover L&L and converting to it's syntax  our demo starter templates.
Things seem to make sense.

I'll disturb you with one more question related to this thread topic.
For rendering, 
as an alternative to your code, 

I see we could also use the PHP function **_tangible_template_**

https://docs.loopsandlogic.com/dynamic-tags/template

Which would be the differences?

**Comment by eliot-akira** [comment]
Let's create a new discussion post for technical questions.

- #129 

By making a separate post for each topic, other people can find the information. And might serve as rough draft for documentation.

**Pull request closed without merging**
